# Generated by Django 4.1.4 on 2022-12-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemId', models.IntegerField()),
                ('BrandId', models.IntegerField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('StoreName', models.CharField(max_length=200)),
                ('CustomerName', models.CharField(max_length=200)),
                ('CreatedOn', models.DateTimeField()),
                ('Status', models.IntegerField(choices=[(10, 'Created'), (20, 'InProgress'), (30, 'Failed'), (40, 'Completed'), (50, 'Canceled'), (60, 'Returned')])),
            ],
        ),
        migrations.CreateModel(
            name='OrderFilterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PageSize', models.IntegerField(default=10)),
                ('PageNumber', models.IntegerField(default=1)),
                ('SearchText', models.CharField(max_length=200)),
                ('StartDate', models.DateTimeField()),
                ('EndDate', models.DateTimeField()),
                ('Statuses', models.JSONField()),
                ('SortBy', models.CharField(max_length=200)),
            ],
        ),
    ]
