# Generated by Django 4.1.4 on 2022-12-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_order_itemid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ItemId',
            field=models.IntegerField(default=1),
        ),
    ]
