# Generated by Django 4.1.4 on 2022-12-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_itemid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ItemId',
            field=models.IntegerField(),
        ),
    ]
