# Generated by Django 4.1.4 on 2022-12-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serverType', models.CharField(max_length=200)),
                ('serverURL', models.URLField()),
            ],
        ),
    ]
